language: node_js
node_js:
- lts/*
cache: npm
script:
- npm run build
after_success:
- eval "$(ssh-agent -s)"
- chmod 600 .travis/deploy.key
- ssh-add .travis/deploy.key
- git remote add deploy ssh://dokku@dokku.hickman.house:3022/snapfit-calculator
- git push deploy
env:
  global:
  - secure: cMHzOsyCOoHtnQhdJ6ZKW8qWaJlrOHtYoWYeoyWrl8hAX9OPfGI9YTnacp1SBkOIHHTf2twLL0H16Hk1NJd4xKQVCQtj2FIh8IdjcRQufm1T4sDmJ467u/873OhjuLqFSxQfwPyccGXZsfn+MQF6hijnBLDaJaKOJKe/UOkKo5KTNR3p3SDHZKyscCJUDiu/lsEJVhJc/uaTlNoboDKu2Lch4GENTwXUUULj5LFHHTyURFjykp/3M3TL4tRDWdwyje3xxZYxf49LgQe3HZhvBEtvjuyQEC8NfDNeN64QW2Yts6D2X8DMRztGqhGUntCIleIXadL3FejK3rQmfYWxapR/cMNtXaBbavFgGIDdTWHGcj8KXt7IDX02Z9zn2wKxiulCsP4wzD5JReiHnloUcHX1Q9yBH3qNIUPiuG/vYc/4CfkKrKpRMa08T4Q8odDyX+maaQeiCjVPPoKHAhImDLP2AK4Uxbl5htnOj4exksv7dqd/Lzse1ower+LCI6vsTFbX5dDu65eSyv+ZgbUYf5V5+b4mcjVynt7NBzupKOUSl6BzrgBFuev+uiapFOcQV7AZyJ9Xg48m8+t/PGL0gOFaC37LEzKDmCz7gpecpQFxg8Wvw8bUFPgOxmlxiQDXmFF0ku3FrzsllBt/T4s8Krv8hiYwnG00cB3OE/08Wpk=
  - secure: pHlQQHdiIFWXyGcqQgGo14lWJFxJXayNO5QCczkqcCzksveoDb0W2YoSdTstupykEFm5mj7BCjc3NdPtErWVSr+axEOgpSnBxQr81EvqB2wzZ6oP6qnzFL8jcbxSLAoU+4YRf7TIWRI5CEiozec+bcpGg0Re4/vrekl+Ky1pYTZMh8C8HaRyy7y+PrJALBd8AZxc+4E+kZ88aKklYE1oT37rzQbexqYs/Iv8ZZ1R9U4YzObRgGeerIwgSnaTZXtn/+bcwH9LRXcaiC2qz0jq+1LmV9Lq6M1R2/bZh0R/7BJ8aFyRAhAzzrSz87/ShVIcgTn4fFofld/f1ioc2P4wyX3fc0LfyENPup7mtJWbjxJDhQshLKGKdyQ7wkxaxBrg/i5c8lJBpvfoYn9Vo26RasAIdY0o7zYUei3PExVWpCRyQs+iXie06X1X6Iil08OTcRgwhCsDXm6AWrBZL1hPqxJ5kPZi3GRiFqqEwrrW6DQx3YGkHwvWTkJ/5dSBX+yiS4J6+w19mncVzefMfiE77F+vUDZIFCtYgvhq1WguI+gnChUd7V/NpzYnHWfoAQyqdratvnmjPU/u671a23DmrrIHk6KLPt2Q+iliJReVo169NjA8BPwLhE/5uySP4Sc0el0YAUGTgzDLir+S3ftZcfXR3GtP8JQB53K8xiZQ45E=
before_install:
- echo $super_secret_password | gpg --passphrase-fd 0 ./.travis/deploy.key.gpg
