language: node_js
node_js:
- lts/*
cache: npm
script:
- npm run build
after_success:
- eval "$(ssh-agent -s)"
- chmod 600 .travis/deploy.key
- ssh-add .travis/deploy.key
- git remote add deploy ssh://dokku@dokku.hickman.house:3022/snapfit-calculator
- git push deploy