language: node_js
node_js:
- lts/*
cache: npm
script:
- npm run build
after_success:
- eval "$(ssh-agent -s)"
- chmod 600 .travis/deploy.key
- ssh-add .travis/deploy.key
- git remote add deploy ssh://dokku@dokku.hickman.house:3022/snapfit-calculator
- git push deploy
before_install:
- openssl aes-256-cbc -K $encrypted_8c5419f7fedf_key -iv $encrypted_8c5419f7fedf_iv
  -in deploy.key.enc -out ./.travis/deploy.key -d
